### ISSUE TITLE
Extension file name mismatch

### ISSUE THREAD

**Issue by ori-bendor** [robofont-mechanic/mechanic-2#27] opened 2020-04-11 00:17 UTC
I cannot use Mechanic to install PangrammerHelper due to what seems to be a file name mismatch. According to the log file (see below), Mechanic expects PangrammerHelper.roboFontExt, but the actual file name is Pangrammer Helper.roboFontExt (with vs without a space).

Other extensions suffer from a similar problem.

Maybe it's a problem with the data fed to Mechanic, but maybe Mechanic can overcome this somehow? (I'm not sure what the data fed to Mechanic looks like, I wasn't able to open any of the json url streams for inspection.)

==

From the log file:

11/04/2020 02:44:08 > ERROR > Mechanic >> Could not find the extension: 'PangrammerHelper.roboFontExt'
11/04/2020 02:44:08 > OUTPUT > ROBOFONT >> Traceback (most recent call last):
11/04/2020 02:44:08 > OUTPUT > ROBOFONT >> File "PyObjCTools/AppHelper.pyc", line 79, in scheduleCallWithDelay_
11/04/2020 02:44:08 > OUTPUT > ROBOFONT >> File "PyObjCTools/AppHelper.pyc", line 97, in performCall
11/04/2020 02:44:08 > OUTPUT > ROBOFONT >> File "/Users/oribendor/Library/Application Support/RoboFont/plugins/Mechanic2.roboFontExt/lib/mechanic2/extensionItem.py", line 208, in _remoteInstallCallback
11/04/2020 02:44:08 > OUTPUT > ROBOFONT >> raise ExtensionRepoError(message)
11/04/2020 02:44:08 > OUTPUT > ROBOFONT >> mechanic2.mechanicTools
11/04/2020 02:44:08 > OUTPUT > ROBOFONT >> .
11/04/2020 02:44:08 > OUTPUT > ROBOFONT >> ExtensionRepoError
11/04/2020 02:44:08 > OUTPUT > ROBOFONT >> :
11/04/2020 02:44:08 > OUTPUT > ROBOFONT >> Could not find the extension: 'PangrammerHelper.roboFontExt'

**Comment by gferreira** [comment] 2020-04-11 09:57
> Other extensions suffer from a similar problem.

please create issues in the [mechanic 2 server] so we can fix them. thanks!

[mechanic 2 server]: http://github.com/robofont-mechanic/mechanic-2-server/issues

**Comment by typemytype** [comment] 2020-04-11 11:33
duplicate, thanks @gferreira 

~~the problem is that the extension path set in mechanic is wrong~~

~~https://github.com/robofont-mechanic/mechanic-2-server/blob/master/_data/pangrammerHelper.yml~~

~~https://github.com/frankrolf/PangrammerHelper~~

**Comment by ori-bendor** [comment] 2020-04-11 14:40
Alright, I've investigated every extension I was forced to download manually in the past year.
At the moment PangrammerHelper is the only extension I'm aware of that suffers from a file name mismatch that Mechanic could easily overcome, so I don't think it's worth adding to Mechanic some clever "let's try to guess the file name" mechanism.
Sorry for all the trouble.

**Comment by frankrolf** [comment] 2020-04-14 16:00
Sorry for adding an extra space.

**Comment by frankrolf** [comment] 2020-04-14 17:45
I will just remove the space in my repo, would that help?

**Comment by frankrolf** [comment] 2020-04-14 17:53
This should be fixed, and can be closed since there is a corresponding issue in Mechanic 2 server:
https://github.com/robofont-mechanic/mechanic-2-server/issues/48

Sorry for the space! 🛰

**Comment by typemytype** [comment] 2020-04-14 17:54
thanks!!

**Closed as completed by typemytype** 2020-04-14 17:54 UTC
